# Generated by Django 5.2 on 2026-02-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='Enter a Description here (optional)', null=True),
        ),
    ]
