# Generated by Django 5.2 on 2026-02-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
